//! Generated closed identifier vocabularies for the protocol catalog. DO NOT EDIT.
//!
//! Regenerated from `specs/operations.toml` by
//! `scripts/generate_red_protocol_catalog.py`. They are used by the generated
//! descriptor catalog but do not implement a wire protocol.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum OperationId {
    ProviderList,
    ProviderShow,
    ProviderSchema,
    MessageSubmit,
    MessageList,
    MessageShow,
    MessageAttemptList,
    MessageCancel,
    DeadLetterList,
    DeadLetterReplay,
    PayloadPurge,
    QueueList,
    ConnectorList,
    ConnectorShow,
    AuditList,
    AdmissionShow,
    AdmissionSet,
    DrainStart,
    ClockShow,
    ClockAcknowledge,
    PrincipalList,
    PrincipalCreate,
    PrincipalShow,
    PrincipalUpdate,
    PrincipalEnable,
    PrincipalDisable,
    GrantList,
    GrantPut,
    GrantDelete,
    ApiKeyList,
    ApiKeyIssue,
    ApiKeyRotate,
    ApiKeyRevoke,
    PeerMappingList,
    PeerMappingCreate,
    PeerMappingShow,
    PeerMappingUpdate,
    PeerMappingDelete,
    ConfigurationShow,
    ConfigurationValidate,
    ConfigurationActivate,
    StateKeyList,
    StateKeyRotate,
    StateKeyRetire,
    RecoveryKeyList,
    RecoveryKeyGenerate,
    RecoveryKeyImport,
    RecoveryKeyRetire,
    BackupList,
    BackupCreate,
    BackupShow,
    BackupManifest,
    BackupDownload,
    BackupCancel,
    BootstrapCreate,
    RestoreCreate,
    RestoreShow,
    RestoreReport,
    RestoreResume,
    StateGenerationList,
    StateGenerationDelete,
    UpgradeShow,
    UpgradePrepare,
    UpgradeMigrate,
    UpgradeActivate,
    UpgradeRollback,
    SystemHealth,
    SystemReadiness,
    SystemMetrics,
    SystemShutdown,
}

impl OperationId {
    #[doc(hidden)]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ProviderList => "provider.list",
            Self::ProviderShow => "provider.show",
            Self::ProviderSchema => "provider.schema",
            Self::MessageSubmit => "message.submit",
            Self::MessageList => "message.list",
            Self::MessageShow => "message.show",
            Self::MessageAttemptList => "message.attempt.list",
            Self::MessageCancel => "message.cancel",
            Self::DeadLetterList => "dead_letter.list",
            Self::DeadLetterReplay => "dead_letter.replay",
            Self::PayloadPurge => "payload.purge",
            Self::QueueList => "queue.list",
            Self::ConnectorList => "connector.list",
            Self::ConnectorShow => "connector.show",
            Self::AuditList => "audit.list",
            Self::AdmissionShow => "admission.show",
            Self::AdmissionSet => "admission.set",
            Self::DrainStart => "drain.start",
            Self::ClockShow => "clock.show",
            Self::ClockAcknowledge => "clock.acknowledge",
            Self::PrincipalList => "principal.list",
            Self::PrincipalCreate => "principal.create",
            Self::PrincipalShow => "principal.show",
            Self::PrincipalUpdate => "principal.update",
            Self::PrincipalEnable => "principal.enable",
            Self::PrincipalDisable => "principal.disable",
            Self::GrantList => "grant.list",
            Self::GrantPut => "grant.put",
            Self::GrantDelete => "grant.delete",
            Self::ApiKeyList => "api_key.list",
            Self::ApiKeyIssue => "api_key.issue",
            Self::ApiKeyRotate => "api_key.rotate",
            Self::ApiKeyRevoke => "api_key.revoke",
            Self::PeerMappingList => "peer_mapping.list",
            Self::PeerMappingCreate => "peer_mapping.create",
            Self::PeerMappingShow => "peer_mapping.show",
            Self::PeerMappingUpdate => "peer_mapping.update",
            Self::PeerMappingDelete => "peer_mapping.delete",
            Self::ConfigurationShow => "configuration.show",
            Self::ConfigurationValidate => "configuration.validate",
            Self::ConfigurationActivate => "configuration.activate",
            Self::StateKeyList => "state_key.list",
            Self::StateKeyRotate => "state_key.rotate",
            Self::StateKeyRetire => "state_key.retire",
            Self::RecoveryKeyList => "recovery_key.list",
            Self::RecoveryKeyGenerate => "recovery_key.generate",
            Self::RecoveryKeyImport => "recovery_key.import",
            Self::RecoveryKeyRetire => "recovery_key.retire",
            Self::BackupList => "backup.list",
            Self::BackupCreate => "backup.create",
            Self::BackupShow => "backup.show",
            Self::BackupManifest => "backup.manifest",
            Self::BackupDownload => "backup.download",
            Self::BackupCancel => "backup.cancel",
            Self::BootstrapCreate => "bootstrap.create",
            Self::RestoreCreate => "restore.create",
            Self::RestoreShow => "restore.show",
            Self::RestoreReport => "restore.report",
            Self::RestoreResume => "restore.resume",
            Self::StateGenerationList => "state_generation.list",
            Self::StateGenerationDelete => "state_generation.delete",
            Self::UpgradeShow => "upgrade.show",
            Self::UpgradePrepare => "upgrade.prepare",
            Self::UpgradeMigrate => "upgrade.migrate",
            Self::UpgradeActivate => "upgrade.activate",
            Self::UpgradeRollback => "upgrade.rollback",
            Self::SystemHealth => "system.health",
            Self::SystemReadiness => "system.readiness",
            Self::SystemMetrics => "system.metrics",
            Self::SystemShutdown => "system.shutdown",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum CodecId {
    BytesConfigurationActivationV1,
    BytesConfigurationCandidateV1,
    JsonAdminActionV1,
    JsonAdmissionV1,
    JsonAdmissionSetV1,
    JsonApiKeyIssueV1,
    JsonApiKeyPageV1,
    JsonApiKeyRevokeResultV1,
    JsonApiKeyRotateV1,
    JsonApiKeySecretOnceV1,
    JsonAttemptPageV1,
    JsonAuditPageV1,
    JsonBackupCreateV1,
    JsonBackupJobV1,
    JsonBackupManifestV1,
    JsonBackupPageV1,
    JsonBootstrapV1,
    JsonBootstrapResultV1,
    JsonClockAcknowledgementV1,
    JsonClockStatusV1,
    JsonConfigurationV1,
    JsonConfigurationActivationV1,
    JsonConfigurationValidationV1,
    JsonConnectorPageV1,
    JsonConnectorStatusV1,
    JsonDeadLetterPageV1,
    JsonDeadLetterReplayV1,
    JsonDrainV1,
    JsonDrainResultV1,
    JsonGenerationGuardedActionV1,
    JsonGrantV1,
    JsonGrantDeleteResultV1,
    JsonGrantPageV1,
    JsonGrantSetV1,
    JsonHealthV1,
    JsonKeyRetirementV1,
    JsonKeyRetirementResultV1,
    JsonMessageAcceptanceV1,
    JsonMessageCancelV1,
    JsonMessagePageV1,
    JsonMessageStatusV1,
    JsonMessageSubmitV1,
    JsonPayloadPurgeV1,
    JsonPayloadPurgeResultV1,
    JsonPeerMappingV1,
    JsonPeerMappingCreateV1,
    JsonPeerMappingDeleteResultV1,
    JsonPeerMappingPageV1,
    JsonPeerMappingUpdateV1,
    JsonPrincipalV1,
    JsonPrincipalCreateV1,
    JsonPrincipalPageV1,
    JsonPrincipalUpdateV1,
    JsonProviderV1,
    JsonProviderPageV1,
    JsonProviderSchemaV1,
    JsonQueuePageV1,
    JsonReadinessV1,
    JsonRecoveryKeyGeneratePhaseV1,
    JsonRecoveryKeyGeneratePhaseResultV1,
    JsonRecoveryKeyImportV1,
    JsonRecoveryKeyMetadataV1,
    JsonRecoveryKeyPageV1,
    JsonRestoreJobV1,
    JsonRestoreReportPageV1,
    JsonRestoreResumeV1,
    JsonRestoreResumeResultV1,
    JsonShutdownV1,
    JsonShutdownAcceptedV1,
    JsonStateGenerationDeleteV1,
    JsonStateGenerationDeleteResultV1,
    JsonStateGenerationPageV1,
    JsonStateKeyPageV1,
    JsonStateKeyRotateV1,
    JsonStateKeyRotationV1,
    JsonUpgradeActivateV1,
    JsonUpgradeMigrateV1,
    JsonUpgradePrepareV1,
    JsonUpgradeRollbackV1,
    JsonUpgradeStatusV1,
    None,
    PathBackupIdV1,
    PathConnectorIdV1,
    PathMessageIdV1,
    PathPeerMappingIdV1,
    PathPrincipalIdV1,
    PathProviderIdV1,
    PathProviderSchemaIdV1,
    PathRestoreIdV1,
    QueryApiKeyListV1,
    QueryAuditListV1,
    QueryBackupListV1,
    QueryConnectorListV1,
    QueryDeadLetterListV1,
    QueryGrantListV1,
    QueryMessageAttemptListV1,
    QueryMessageListV1,
    QueryPeerMappingListV1,
    QueryPrincipalListV1,
    QueryProviderListV1,
    QueryQueueListV1,
    QueryRecoveryKeyListV1,
    QueryRestoreReportPageV1,
    QueryStateGenerationListV1,
    QueryStateKeyListV1,
    StreamBackupArtifactV1,
    StreamRestoreArtifactV1,
    TextMetricsV1,
}

impl CodecId {
    #[doc(hidden)]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::BytesConfigurationActivationV1 => "bytes.configuration_activation.v1",
            Self::BytesConfigurationCandidateV1 => "bytes.configuration_candidate.v1",
            Self::JsonAdminActionV1 => "json.admin_action.v1",
            Self::JsonAdmissionV1 => "json.admission.v1",
            Self::JsonAdmissionSetV1 => "json.admission_set.v1",
            Self::JsonApiKeyIssueV1 => "json.api_key_issue.v1",
            Self::JsonApiKeyPageV1 => "json.api_key_page.v1",
            Self::JsonApiKeyRevokeResultV1 => "json.api_key_revoke_result.v1",
            Self::JsonApiKeyRotateV1 => "json.api_key_rotate.v1",
            Self::JsonApiKeySecretOnceV1 => "json.api_key_secret_once.v1",
            Self::JsonAttemptPageV1 => "json.attempt_page.v1",
            Self::JsonAuditPageV1 => "json.audit_page.v1",
            Self::JsonBackupCreateV1 => "json.backup_create.v1",
            Self::JsonBackupJobV1 => "json.backup_job.v1",
            Self::JsonBackupManifestV1 => "json.backup_manifest.v1",
            Self::JsonBackupPageV1 => "json.backup_page.v1",
            Self::JsonBootstrapV1 => "json.bootstrap.v1",
            Self::JsonBootstrapResultV1 => "json.bootstrap_result.v1",
            Self::JsonClockAcknowledgementV1 => "json.clock_acknowledgement.v1",
            Self::JsonClockStatusV1 => "json.clock_status.v1",
            Self::JsonConfigurationV1 => "json.configuration.v1",
            Self::JsonConfigurationActivationV1 => "json.configuration_activation.v1",
            Self::JsonConfigurationValidationV1 => "json.configuration_validation.v1",
            Self::JsonConnectorPageV1 => "json.connector_page.v1",
            Self::JsonConnectorStatusV1 => "json.connector_status.v1",
            Self::JsonDeadLetterPageV1 => "json.dead_letter_page.v1",
            Self::JsonDeadLetterReplayV1 => "json.dead_letter_replay.v1",
            Self::JsonDrainV1 => "json.drain.v1",
            Self::JsonDrainResultV1 => "json.drain_result.v1",
            Self::JsonGenerationGuardedActionV1 => "json.generation_guarded_action.v1",
            Self::JsonGrantV1 => "json.grant.v1",
            Self::JsonGrantDeleteResultV1 => "json.grant_delete_result.v1",
            Self::JsonGrantPageV1 => "json.grant_page.v1",
            Self::JsonGrantSetV1 => "json.grant_set.v1",
            Self::JsonHealthV1 => "json.health.v1",
            Self::JsonKeyRetirementV1 => "json.key_retirement.v1",
            Self::JsonKeyRetirementResultV1 => "json.key_retirement_result.v1",
            Self::JsonMessageAcceptanceV1 => "json.message_acceptance.v1",
            Self::JsonMessageCancelV1 => "json.message_cancel.v1",
            Self::JsonMessagePageV1 => "json.message_page.v1",
            Self::JsonMessageStatusV1 => "json.message_status.v1",
            Self::JsonMessageSubmitV1 => "json.message_submit.v1",
            Self::JsonPayloadPurgeV1 => "json.payload_purge.v1",
            Self::JsonPayloadPurgeResultV1 => "json.payload_purge_result.v1",
            Self::JsonPeerMappingV1 => "json.peer_mapping.v1",
            Self::JsonPeerMappingCreateV1 => "json.peer_mapping_create.v1",
            Self::JsonPeerMappingDeleteResultV1 => "json.peer_mapping_delete_result.v1",
            Self::JsonPeerMappingPageV1 => "json.peer_mapping_page.v1",
            Self::JsonPeerMappingUpdateV1 => "json.peer_mapping_update.v1",
            Self::JsonPrincipalV1 => "json.principal.v1",
            Self::JsonPrincipalCreateV1 => "json.principal_create.v1",
            Self::JsonPrincipalPageV1 => "json.principal_page.v1",
            Self::JsonPrincipalUpdateV1 => "json.principal_update.v1",
            Self::JsonProviderV1 => "json.provider.v1",
            Self::JsonProviderPageV1 => "json.provider_page.v1",
            Self::JsonProviderSchemaV1 => "json.provider_schema.v1",
            Self::JsonQueuePageV1 => "json.queue_page.v1",
            Self::JsonReadinessV1 => "json.readiness.v1",
            Self::JsonRecoveryKeyGeneratePhaseV1 => "json.recovery_key_generate_phase.v1",
            Self::JsonRecoveryKeyGeneratePhaseResultV1 => {
                "json.recovery_key_generate_phase_result.v1"
            }
            Self::JsonRecoveryKeyImportV1 => "json.recovery_key_import.v1",
            Self::JsonRecoveryKeyMetadataV1 => "json.recovery_key_metadata.v1",
            Self::JsonRecoveryKeyPageV1 => "json.recovery_key_page.v1",
            Self::JsonRestoreJobV1 => "json.restore_job.v1",
            Self::JsonRestoreReportPageV1 => "json.restore_report_page.v1",
            Self::JsonRestoreResumeV1 => "json.restore_resume.v1",
            Self::JsonRestoreResumeResultV1 => "json.restore_resume_result.v1",
            Self::JsonShutdownV1 => "json.shutdown.v1",
            Self::JsonShutdownAcceptedV1 => "json.shutdown_accepted.v1",
            Self::JsonStateGenerationDeleteV1 => "json.state_generation_delete.v1",
            Self::JsonStateGenerationDeleteResultV1 => "json.state_generation_delete_result.v1",
            Self::JsonStateGenerationPageV1 => "json.state_generation_page.v1",
            Self::JsonStateKeyPageV1 => "json.state_key_page.v1",
            Self::JsonStateKeyRotateV1 => "json.state_key_rotate.v1",
            Self::JsonStateKeyRotationV1 => "json.state_key_rotation.v1",
            Self::JsonUpgradeActivateV1 => "json.upgrade_activate.v1",
            Self::JsonUpgradeMigrateV1 => "json.upgrade_migrate.v1",
            Self::JsonUpgradePrepareV1 => "json.upgrade_prepare.v1",
            Self::JsonUpgradeRollbackV1 => "json.upgrade_rollback.v1",
            Self::JsonUpgradeStatusV1 => "json.upgrade_status.v1",
            Self::None => "none",
            Self::PathBackupIdV1 => "path.backup_id.v1",
            Self::PathConnectorIdV1 => "path.connector_id.v1",
            Self::PathMessageIdV1 => "path.message_id.v1",
            Self::PathPeerMappingIdV1 => "path.peer_mapping_id.v1",
            Self::PathPrincipalIdV1 => "path.principal_id.v1",
            Self::PathProviderIdV1 => "path.provider_id.v1",
            Self::PathProviderSchemaIdV1 => "path.provider_schema_id.v1",
            Self::PathRestoreIdV1 => "path.restore_id.v1",
            Self::QueryApiKeyListV1 => "query.api_key_list.v1",
            Self::QueryAuditListV1 => "query.audit_list.v1",
            Self::QueryBackupListV1 => "query.backup_list.v1",
            Self::QueryConnectorListV1 => "query.connector_list.v1",
            Self::QueryDeadLetterListV1 => "query.dead_letter_list.v1",
            Self::QueryGrantListV1 => "query.grant_list.v1",
            Self::QueryMessageAttemptListV1 => "query.message_attempt_list.v1",
            Self::QueryMessageListV1 => "query.message_list.v1",
            Self::QueryPeerMappingListV1 => "query.peer_mapping_list.v1",
            Self::QueryPrincipalListV1 => "query.principal_list.v1",
            Self::QueryProviderListV1 => "query.provider_list.v1",
            Self::QueryQueueListV1 => "query.queue_list.v1",
            Self::QueryRecoveryKeyListV1 => "query.recovery_key_list.v1",
            Self::QueryRestoreReportPageV1 => "query.restore_report_page.v1",
            Self::QueryStateGenerationListV1 => "query.state_generation_list.v1",
            Self::QueryStateKeyListV1 => "query.state_key_list.v1",
            Self::StreamBackupArtifactV1 => "stream.backup_artifact.v1",
            Self::StreamRestoreArtifactV1 => "stream.restore_artifact.v1",
            Self::TextMetricsV1 => "text.metrics.v1",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum HttpMethod {
    Delete,
    Get,
    Patch,
    Post,
    Put,
}

impl HttpMethod {
    #[doc(hidden)]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Delete => "DELETE",
            Self::Get => "GET",
            Self::Patch => "PATCH",
            Self::Post => "POST",
            Self::Put => "PUT",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Binding {
    MaintenanceUds,
    NormalTcp,
    NormalUds,
}

impl Binding {
    #[doc(hidden)]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::MaintenanceUds => "maintenance_uds",
            Self::NormalTcp => "normal_tcp",
            Self::NormalUds => "normal_uds",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Authorization {
    AuthenticatedCatalog,
    CancelOwnOrOperator,
    LocalOperator,
    LocalOperatorOrStateOwnerPeer,
    LocalRecoveryOperator,
    Operator,
    ProbeByBinding,
    StateOwnerPeer,
    StatusOwnOrOperator,
    Submit,
}

impl Authorization {
    #[doc(hidden)]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::AuthenticatedCatalog => "authenticated_catalog",
            Self::CancelOwnOrOperator => "cancel_own_or_operator",
            Self::LocalOperator => "local_operator",
            Self::LocalOperatorOrStateOwnerPeer => "local_operator_or_state_owner_peer",
            Self::LocalRecoveryOperator => "local_recovery_operator",
            Self::Operator => "operator",
            Self::ProbeByBinding => "probe_by_binding",
            Self::StateOwnerPeer => "state_owner_peer",
            Self::StatusOwnOrOperator => "status_own_or_operator",
            Self::Submit => "submit",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Idempotency {
    AddressedState,
    CommandKey,
    DomainKey,
    GenerationGuarded,
    IdempotentAction,
    OneTimeSecret,
    Safe,
    SafeCalculation,
}

impl Idempotency {
    #[doc(hidden)]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::AddressedState => "addressed_state",
            Self::CommandKey => "command_key",
            Self::DomainKey => "domain_key",
            Self::GenerationGuarded => "generation_guarded",
            Self::IdempotentAction => "idempotent_action",
            Self::OneTimeSecret => "one_time_secret",
            Self::Safe => "safe",
            Self::SafeCalculation => "safe_calculation",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Risk {
    AuthorizationChange,
    ConfigurationChange,
    CredentialIssue,
    CryptographicChange,
    Destructive,
    ExternalEffect,
    Mutation,
    Read,
    ResourceIntensive,
    ReversibleControl,
    SafetyControl,
    SafetyOverride,
    SensitiveRead,
}

impl Risk {
    #[doc(hidden)]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::AuthorizationChange => "authorization_change",
            Self::ConfigurationChange => "configuration_change",
            Self::CredentialIssue => "credential_issue",
            Self::CryptographicChange => "cryptographic_change",
            Self::Destructive => "destructive",
            Self::ExternalEffect => "external_effect",
            Self::Mutation => "mutation",
            Self::Read => "read",
            Self::ResourceIntensive => "resource_intensive",
            Self::ReversibleControl => "reversible_control",
            Self::SafetyControl => "safety_control",
            Self::SafetyOverride => "safety_override",
            Self::SensitiveRead => "sensitive_read",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum OneTimeMode {
    EscrowAcknowledgement,
    SinglePhase,
}

impl OneTimeMode {
    #[doc(hidden)]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::EscrowAcknowledgement => "escrow_acknowledgement",
            Self::SinglePhase => "single_phase",
        }
    }
}
