//! Generated exact operation descriptors. DO NOT EDIT.
//!
//! Regenerated from `specs/operations.toml` by
//! `scripts/generate_red_protocol_catalog.py`. This is catalog metadata only:
//! it selects no route, parses no codec, and performs no authorization or I/O.

use crate::{
    Authorization, Binding, CodecId, HttpMethod, Idempotency, OneTimeMode, OperationDescriptor,
    OperationId, Risk,
};

pub(crate) static OPERATION_CATALOG: &[OperationDescriptor] = &[
    OperationDescriptor {
        id: OperationId::ProviderList,
        method: HttpMethod::Get,
        path: "/v1/providers",
        bindings: &[Binding::NormalUds, Binding::NormalTcp],
        authorization: Authorization::AuthenticatedCatalog,
        request_codec: CodecId::QueryProviderListV1,
        response_codec: Some(CodecId::JsonProviderPageV1),
        idempotency: Idempotency::Safe,
        risk: Risk::Read,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::ProviderShow,
        method: HttpMethod::Get,
        path: "/v1/providers/{provider_id}",
        bindings: &[Binding::NormalUds, Binding::NormalTcp],
        authorization: Authorization::AuthenticatedCatalog,
        request_codec: CodecId::PathProviderIdV1,
        response_codec: Some(CodecId::JsonProviderV1),
        idempotency: Idempotency::Safe,
        risk: Risk::Read,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::ProviderSchema,
        method: HttpMethod::Get,
        path: "/v1/providers/{provider_id}/schemas/{schema_id}",
        bindings: &[Binding::NormalUds, Binding::NormalTcp],
        authorization: Authorization::AuthenticatedCatalog,
        request_codec: CodecId::PathProviderSchemaIdV1,
        response_codec: Some(CodecId::JsonProviderSchemaV1),
        idempotency: Idempotency::Safe,
        risk: Risk::Read,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::MessageSubmit,
        method: HttpMethod::Post,
        path: "/v1/messages",
        bindings: &[Binding::NormalUds, Binding::NormalTcp],
        authorization: Authorization::Submit,
        request_codec: CodecId::JsonMessageSubmitV1,
        response_codec: Some(CodecId::JsonMessageAcceptanceV1),
        idempotency: Idempotency::DomainKey,
        risk: Risk::ExternalEffect,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::MessageList,
        method: HttpMethod::Get,
        path: "/v1/messages",
        bindings: &[Binding::NormalUds, Binding::NormalTcp],
        authorization: Authorization::StatusOwnOrOperator,
        request_codec: CodecId::QueryMessageListV1,
        response_codec: Some(CodecId::JsonMessagePageV1),
        idempotency: Idempotency::Safe,
        risk: Risk::Read,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::MessageShow,
        method: HttpMethod::Get,
        path: "/v1/messages/{message_id}",
        bindings: &[Binding::NormalUds, Binding::NormalTcp],
        authorization: Authorization::StatusOwnOrOperator,
        request_codec: CodecId::PathMessageIdV1,
        response_codec: Some(CodecId::JsonMessageStatusV1),
        idempotency: Idempotency::Safe,
        risk: Risk::Read,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::MessageAttemptList,
        method: HttpMethod::Get,
        path: "/v1/messages/{message_id}/attempts",
        bindings: &[Binding::NormalUds, Binding::NormalTcp],
        authorization: Authorization::StatusOwnOrOperator,
        request_codec: CodecId::QueryMessageAttemptListV1,
        response_codec: Some(CodecId::JsonAttemptPageV1),
        idempotency: Idempotency::Safe,
        risk: Risk::Read,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::MessageCancel,
        method: HttpMethod::Post,
        path: "/v1/messages/{message_id}/cancel",
        bindings: &[Binding::NormalUds, Binding::NormalTcp],
        authorization: Authorization::CancelOwnOrOperator,
        request_codec: CodecId::JsonMessageCancelV1,
        response_codec: Some(CodecId::JsonMessageStatusV1),
        idempotency: Idempotency::IdempotentAction,
        risk: Risk::Mutation,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::DeadLetterList,
        method: HttpMethod::Get,
        path: "/v1/dead-letters",
        bindings: &[Binding::NormalUds, Binding::NormalTcp],
        authorization: Authorization::Operator,
        request_codec: CodecId::QueryDeadLetterListV1,
        response_codec: Some(CodecId::JsonDeadLetterPageV1),
        idempotency: Idempotency::Safe,
        risk: Risk::Read,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::DeadLetterReplay,
        method: HttpMethod::Post,
        path: "/v1/dead-letters/{message_id}/replays",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::JsonDeadLetterReplayV1,
        response_codec: Some(CodecId::JsonMessageAcceptanceV1),
        idempotency: Idempotency::DomainKey,
        risk: Risk::ExternalEffect,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::PayloadPurge,
        method: HttpMethod::Delete,
        path: "/v1/messages/{message_id}/payload",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::JsonPayloadPurgeV1,
        response_codec: Some(CodecId::JsonPayloadPurgeResultV1),
        idempotency: Idempotency::IdempotentAction,
        risk: Risk::Destructive,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::QueueList,
        method: HttpMethod::Get,
        path: "/v1/admin/queue",
        bindings: &[Binding::NormalUds, Binding::NormalTcp],
        authorization: Authorization::Operator,
        request_codec: CodecId::QueryQueueListV1,
        response_codec: Some(CodecId::JsonQueuePageV1),
        idempotency: Idempotency::Safe,
        risk: Risk::Read,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::ConnectorList,
        method: HttpMethod::Get,
        path: "/v1/admin/connectors",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::QueryConnectorListV1,
        response_codec: Some(CodecId::JsonConnectorPageV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::ConnectorShow,
        method: HttpMethod::Get,
        path: "/v1/admin/connectors/{connector_id}",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::PathConnectorIdV1,
        response_codec: Some(CodecId::JsonConnectorStatusV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::AuditList,
        method: HttpMethod::Get,
        path: "/v1/admin/audit-events",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::QueryAuditListV1,
        response_codec: Some(CodecId::JsonAuditPageV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::AdmissionShow,
        method: HttpMethod::Get,
        path: "/v1/admin/admission",
        bindings: &[Binding::NormalUds, Binding::NormalTcp],
        authorization: Authorization::Operator,
        request_codec: CodecId::None,
        response_codec: Some(CodecId::JsonAdmissionV1),
        idempotency: Idempotency::Safe,
        risk: Risk::Read,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::AdmissionSet,
        method: HttpMethod::Put,
        path: "/v1/admin/admission",
        bindings: &[Binding::NormalUds, Binding::NormalTcp],
        authorization: Authorization::Operator,
        request_codec: CodecId::JsonAdmissionSetV1,
        response_codec: Some(CodecId::JsonAdmissionV1),
        idempotency: Idempotency::GenerationGuarded,
        risk: Risk::ReversibleControl,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::DrainStart,
        method: HttpMethod::Post,
        path: "/v1/admin/drains",
        bindings: &[Binding::NormalUds, Binding::NormalTcp],
        authorization: Authorization::Operator,
        request_codec: CodecId::JsonDrainV1,
        response_codec: Some(CodecId::JsonDrainResultV1),
        idempotency: Idempotency::CommandKey,
        risk: Risk::ReversibleControl,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::ClockShow,
        method: HttpMethod::Get,
        path: "/v1/admin/clock",
        bindings: &[Binding::NormalUds, Binding::MaintenanceUds],
        authorization: Authorization::LocalOperatorOrStateOwnerPeer,
        request_codec: CodecId::None,
        response_codec: Some(CodecId::JsonClockStatusV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::ClockAcknowledge,
        method: HttpMethod::Post,
        path: "/v1/admin/clock-acknowledgements",
        bindings: &[Binding::NormalUds, Binding::MaintenanceUds],
        authorization: Authorization::LocalOperatorOrStateOwnerPeer,
        request_codec: CodecId::JsonClockAcknowledgementV1,
        response_codec: Some(CodecId::JsonClockStatusV1),
        idempotency: Idempotency::AddressedState,
        risk: Risk::SafetyOverride,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::PrincipalList,
        method: HttpMethod::Get,
        path: "/v1/admin/principals",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::QueryPrincipalListV1,
        response_codec: Some(CodecId::JsonPrincipalPageV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::PrincipalCreate,
        method: HttpMethod::Post,
        path: "/v1/admin/principals",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::JsonPrincipalCreateV1,
        response_codec: Some(CodecId::JsonPrincipalV1),
        idempotency: Idempotency::CommandKey,
        risk: Risk::AuthorizationChange,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::PrincipalShow,
        method: HttpMethod::Get,
        path: "/v1/admin/principals/{principal_id}",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::PathPrincipalIdV1,
        response_codec: Some(CodecId::JsonPrincipalV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::PrincipalUpdate,
        method: HttpMethod::Patch,
        path: "/v1/admin/principals/{principal_id}",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::JsonPrincipalUpdateV1,
        response_codec: Some(CodecId::JsonPrincipalV1),
        idempotency: Idempotency::CommandKey,
        risk: Risk::AuthorizationChange,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::PrincipalEnable,
        method: HttpMethod::Post,
        path: "/v1/admin/principals/{principal_id}/enable",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::JsonGenerationGuardedActionV1,
        response_codec: Some(CodecId::JsonPrincipalV1),
        idempotency: Idempotency::GenerationGuarded,
        risk: Risk::AuthorizationChange,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::PrincipalDisable,
        method: HttpMethod::Post,
        path: "/v1/admin/principals/{principal_id}/disable",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::JsonGenerationGuardedActionV1,
        response_codec: Some(CodecId::JsonPrincipalV1),
        idempotency: Idempotency::GenerationGuarded,
        risk: Risk::AuthorizationChange,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::GrantList,
        method: HttpMethod::Get,
        path: "/v1/admin/principals/{principal_id}/provider-grants",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::QueryGrantListV1,
        response_codec: Some(CodecId::JsonGrantPageV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::GrantPut,
        method: HttpMethod::Put,
        path: "/v1/admin/principals/{principal_id}/provider-grants/{provider_id}",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::JsonGrantSetV1,
        response_codec: Some(CodecId::JsonGrantV1),
        idempotency: Idempotency::GenerationGuarded,
        risk: Risk::AuthorizationChange,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::GrantDelete,
        method: HttpMethod::Delete,
        path: "/v1/admin/principals/{principal_id}/provider-grants/{provider_id}",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::JsonGenerationGuardedActionV1,
        response_codec: Some(CodecId::JsonGrantDeleteResultV1),
        idempotency: Idempotency::GenerationGuarded,
        risk: Risk::AuthorizationChange,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::ApiKeyList,
        method: HttpMethod::Get,
        path: "/v1/admin/api-keys",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::QueryApiKeyListV1,
        response_codec: Some(CodecId::JsonApiKeyPageV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::ApiKeyIssue,
        method: HttpMethod::Post,
        path: "/v1/admin/api-keys",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::JsonApiKeyIssueV1,
        response_codec: Some(CodecId::JsonApiKeySecretOnceV1),
        idempotency: Idempotency::OneTimeSecret,
        risk: Risk::CredentialIssue,
        one_time_mode: Some(OneTimeMode::SinglePhase),
    },
    OperationDescriptor {
        id: OperationId::ApiKeyRotate,
        method: HttpMethod::Post,
        path: "/v1/admin/api-keys/{key_id}/rotations",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::JsonApiKeyRotateV1,
        response_codec: Some(CodecId::JsonApiKeySecretOnceV1),
        idempotency: Idempotency::OneTimeSecret,
        risk: Risk::CredentialIssue,
        one_time_mode: Some(OneTimeMode::SinglePhase),
    },
    OperationDescriptor {
        id: OperationId::ApiKeyRevoke,
        method: HttpMethod::Delete,
        path: "/v1/admin/api-keys/{key_id}",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::JsonAdminActionV1,
        response_codec: Some(CodecId::JsonApiKeyRevokeResultV1),
        idempotency: Idempotency::IdempotentAction,
        risk: Risk::AuthorizationChange,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::PeerMappingList,
        method: HttpMethod::Get,
        path: "/v1/admin/peer-mappings",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::QueryPeerMappingListV1,
        response_codec: Some(CodecId::JsonPeerMappingPageV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::PeerMappingCreate,
        method: HttpMethod::Post,
        path: "/v1/admin/peer-mappings",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::JsonPeerMappingCreateV1,
        response_codec: Some(CodecId::JsonPeerMappingV1),
        idempotency: Idempotency::CommandKey,
        risk: Risk::AuthorizationChange,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::PeerMappingShow,
        method: HttpMethod::Get,
        path: "/v1/admin/peer-mappings/{mapping_id}",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::PathPeerMappingIdV1,
        response_codec: Some(CodecId::JsonPeerMappingV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::PeerMappingUpdate,
        method: HttpMethod::Patch,
        path: "/v1/admin/peer-mappings/{mapping_id}",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::JsonPeerMappingUpdateV1,
        response_codec: Some(CodecId::JsonPeerMappingV1),
        idempotency: Idempotency::CommandKey,
        risk: Risk::AuthorizationChange,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::PeerMappingDelete,
        method: HttpMethod::Delete,
        path: "/v1/admin/peer-mappings/{mapping_id}",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::JsonAdminActionV1,
        response_codec: Some(CodecId::JsonPeerMappingDeleteResultV1),
        idempotency: Idempotency::IdempotentAction,
        risk: Risk::AuthorizationChange,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::ConfigurationShow,
        method: HttpMethod::Get,
        path: "/v1/admin/configuration",
        bindings: &[Binding::NormalUds, Binding::MaintenanceUds],
        authorization: Authorization::LocalOperatorOrStateOwnerPeer,
        request_codec: CodecId::None,
        response_codec: Some(CodecId::JsonConfigurationV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::ConfigurationValidate,
        method: HttpMethod::Post,
        path: "/v1/admin/config-validations",
        bindings: &[Binding::NormalUds, Binding::MaintenanceUds],
        authorization: Authorization::LocalOperatorOrStateOwnerPeer,
        request_codec: CodecId::BytesConfigurationCandidateV1,
        response_codec: Some(CodecId::JsonConfigurationValidationV1),
        idempotency: Idempotency::SafeCalculation,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::ConfigurationActivate,
        method: HttpMethod::Put,
        path: "/v1/admin/configuration",
        bindings: &[Binding::MaintenanceUds],
        authorization: Authorization::StateOwnerPeer,
        request_codec: CodecId::BytesConfigurationActivationV1,
        response_codec: Some(CodecId::JsonConfigurationActivationV1),
        idempotency: Idempotency::CommandKey,
        risk: Risk::ConfigurationChange,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::StateKeyList,
        method: HttpMethod::Get,
        path: "/v1/admin/state-keys",
        bindings: &[Binding::MaintenanceUds],
        authorization: Authorization::StateOwnerPeer,
        request_codec: CodecId::QueryStateKeyListV1,
        response_codec: Some(CodecId::JsonStateKeyPageV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::StateKeyRotate,
        method: HttpMethod::Post,
        path: "/v1/admin/state-keys/{purpose}/rotations",
        bindings: &[Binding::MaintenanceUds],
        authorization: Authorization::StateOwnerPeer,
        request_codec: CodecId::JsonStateKeyRotateV1,
        response_codec: Some(CodecId::JsonStateKeyRotationV1),
        idempotency: Idempotency::CommandKey,
        risk: Risk::CryptographicChange,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::StateKeyRetire,
        method: HttpMethod::Delete,
        path: "/v1/admin/state-keys/{purpose}/{generation_id}",
        bindings: &[Binding::MaintenanceUds],
        authorization: Authorization::StateOwnerPeer,
        request_codec: CodecId::JsonKeyRetirementV1,
        response_codec: Some(CodecId::JsonKeyRetirementResultV1),
        idempotency: Idempotency::CommandKey,
        risk: Risk::Destructive,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::RecoveryKeyList,
        method: HttpMethod::Get,
        path: "/v1/admin/recovery-keys",
        bindings: &[Binding::MaintenanceUds],
        authorization: Authorization::StateOwnerPeer,
        request_codec: CodecId::QueryRecoveryKeyListV1,
        response_codec: Some(CodecId::JsonRecoveryKeyPageV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::RecoveryKeyGenerate,
        method: HttpMethod::Post,
        path: "/v1/admin/recovery-keys",
        bindings: &[Binding::MaintenanceUds],
        authorization: Authorization::StateOwnerPeer,
        request_codec: CodecId::JsonRecoveryKeyGeneratePhaseV1,
        response_codec: Some(CodecId::JsonRecoveryKeyGeneratePhaseResultV1),
        idempotency: Idempotency::OneTimeSecret,
        risk: Risk::CredentialIssue,
        one_time_mode: Some(OneTimeMode::EscrowAcknowledgement),
    },
    OperationDescriptor {
        id: OperationId::RecoveryKeyImport,
        method: HttpMethod::Post,
        path: "/v1/admin/recovery-key-imports",
        bindings: &[Binding::MaintenanceUds],
        authorization: Authorization::StateOwnerPeer,
        request_codec: CodecId::JsonRecoveryKeyImportV1,
        response_codec: Some(CodecId::JsonRecoveryKeyMetadataV1),
        idempotency: Idempotency::CommandKey,
        risk: Risk::CryptographicChange,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::RecoveryKeyRetire,
        method: HttpMethod::Delete,
        path: "/v1/admin/recovery-keys/{generation_id}",
        bindings: &[Binding::MaintenanceUds],
        authorization: Authorization::StateOwnerPeer,
        request_codec: CodecId::JsonKeyRetirementV1,
        response_codec: Some(CodecId::JsonKeyRetirementResultV1),
        idempotency: Idempotency::CommandKey,
        risk: Risk::Destructive,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::BackupList,
        method: HttpMethod::Get,
        path: "/v1/admin/backups",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::QueryBackupListV1,
        response_codec: Some(CodecId::JsonBackupPageV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::BackupCreate,
        method: HttpMethod::Post,
        path: "/v1/admin/backups",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::JsonBackupCreateV1,
        response_codec: Some(CodecId::JsonBackupJobV1),
        idempotency: Idempotency::CommandKey,
        risk: Risk::ResourceIntensive,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::BackupShow,
        method: HttpMethod::Get,
        path: "/v1/admin/backups/{backup_id}",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::PathBackupIdV1,
        response_codec: Some(CodecId::JsonBackupJobV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::BackupManifest,
        method: HttpMethod::Get,
        path: "/v1/admin/backups/{backup_id}/manifest",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::PathBackupIdV1,
        response_codec: Some(CodecId::JsonBackupManifestV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::BackupDownload,
        method: HttpMethod::Get,
        path: "/v1/admin/backups/{backup_id}/artifact",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::PathBackupIdV1,
        response_codec: Some(CodecId::StreamBackupArtifactV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::BackupCancel,
        method: HttpMethod::Post,
        path: "/v1/admin/backups/{backup_id}/cancel",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::JsonAdminActionV1,
        response_codec: Some(CodecId::JsonBackupJobV1),
        idempotency: Idempotency::IdempotentAction,
        risk: Risk::Mutation,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::BootstrapCreate,
        method: HttpMethod::Post,
        path: "/v1/admin/bootstrap",
        bindings: &[Binding::MaintenanceUds],
        authorization: Authorization::StateOwnerPeer,
        request_codec: CodecId::JsonBootstrapV1,
        response_codec: Some(CodecId::JsonBootstrapResultV1),
        idempotency: Idempotency::CommandKey,
        risk: Risk::ConfigurationChange,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::RestoreCreate,
        method: HttpMethod::Post,
        path: "/v1/admin/restores",
        bindings: &[Binding::MaintenanceUds],
        authorization: Authorization::StateOwnerPeer,
        request_codec: CodecId::StreamRestoreArtifactV1,
        response_codec: Some(CodecId::JsonRestoreJobV1),
        idempotency: Idempotency::CommandKey,
        risk: Risk::Destructive,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::RestoreShow,
        method: HttpMethod::Get,
        path: "/v1/admin/restores/{restore_id}",
        bindings: &[Binding::MaintenanceUds],
        authorization: Authorization::StateOwnerPeer,
        request_codec: CodecId::PathRestoreIdV1,
        response_codec: Some(CodecId::JsonRestoreJobV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::RestoreReport,
        method: HttpMethod::Get,
        path: "/v1/admin/restores/current",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::QueryRestoreReportPageV1,
        response_codec: Some(CodecId::JsonRestoreReportPageV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::RestoreResume,
        method: HttpMethod::Post,
        path: "/v1/admin/restores/current/resume",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalRecoveryOperator,
        request_codec: CodecId::JsonRestoreResumeV1,
        response_codec: Some(CodecId::JsonRestoreResumeResultV1),
        idempotency: Idempotency::CommandKey,
        risk: Risk::SafetyOverride,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::StateGenerationList,
        method: HttpMethod::Get,
        path: "/v1/admin/state-generations",
        bindings: &[Binding::MaintenanceUds],
        authorization: Authorization::StateOwnerPeer,
        request_codec: CodecId::QueryStateGenerationListV1,
        response_codec: Some(CodecId::JsonStateGenerationPageV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::StateGenerationDelete,
        method: HttpMethod::Delete,
        path: "/v1/admin/state-generations/{generation_id}",
        bindings: &[Binding::MaintenanceUds],
        authorization: Authorization::StateOwnerPeer,
        request_codec: CodecId::JsonStateGenerationDeleteV1,
        response_codec: Some(CodecId::JsonStateGenerationDeleteResultV1),
        idempotency: Idempotency::CommandKey,
        risk: Risk::Destructive,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::UpgradeShow,
        method: HttpMethod::Get,
        path: "/v1/admin/upgrade",
        bindings: &[Binding::NormalUds, Binding::MaintenanceUds],
        authorization: Authorization::LocalOperatorOrStateOwnerPeer,
        request_codec: CodecId::None,
        response_codec: Some(CodecId::JsonUpgradeStatusV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::UpgradePrepare,
        method: HttpMethod::Post,
        path: "/v1/admin/upgrades",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::JsonUpgradePrepareV1,
        response_codec: Some(CodecId::JsonUpgradeStatusV1),
        idempotency: Idempotency::CommandKey,
        risk: Risk::SafetyControl,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::UpgradeMigrate,
        method: HttpMethod::Post,
        path: "/v1/admin/upgrades/{upgrade_id}/migration",
        bindings: &[Binding::MaintenanceUds],
        authorization: Authorization::StateOwnerPeer,
        request_codec: CodecId::JsonUpgradeMigrateV1,
        response_codec: Some(CodecId::JsonUpgradeStatusV1),
        idempotency: Idempotency::CommandKey,
        risk: Risk::Destructive,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::UpgradeActivate,
        method: HttpMethod::Post,
        path: "/v1/admin/upgrades/{upgrade_id}/activation",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::JsonUpgradeActivateV1,
        response_codec: Some(CodecId::JsonUpgradeStatusV1),
        idempotency: Idempotency::CommandKey,
        risk: Risk::SafetyOverride,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::UpgradeRollback,
        method: HttpMethod::Post,
        path: "/v1/admin/upgrades/{upgrade_id}/rollback",
        bindings: &[Binding::MaintenanceUds],
        authorization: Authorization::StateOwnerPeer,
        request_codec: CodecId::JsonUpgradeRollbackV1,
        response_codec: Some(CodecId::JsonUpgradeStatusV1),
        idempotency: Idempotency::CommandKey,
        risk: Risk::Destructive,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::SystemHealth,
        method: HttpMethod::Get,
        path: "/v1/system/health",
        bindings: &[
            Binding::NormalUds,
            Binding::NormalTcp,
            Binding::MaintenanceUds,
        ],
        authorization: Authorization::ProbeByBinding,
        request_codec: CodecId::None,
        response_codec: Some(CodecId::JsonHealthV1),
        idempotency: Idempotency::Safe,
        risk: Risk::Read,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::SystemReadiness,
        method: HttpMethod::Get,
        path: "/v1/system/readiness",
        bindings: &[
            Binding::NormalUds,
            Binding::NormalTcp,
            Binding::MaintenanceUds,
        ],
        authorization: Authorization::ProbeByBinding,
        request_codec: CodecId::None,
        response_codec: Some(CodecId::JsonReadinessV1),
        idempotency: Idempotency::Safe,
        risk: Risk::Read,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::SystemMetrics,
        method: HttpMethod::Get,
        path: "/v1/system/metrics",
        bindings: &[Binding::NormalUds],
        authorization: Authorization::LocalOperator,
        request_codec: CodecId::None,
        response_codec: Some(CodecId::TextMetricsV1),
        idempotency: Idempotency::Safe,
        risk: Risk::SensitiveRead,
        one_time_mode: None,
    },
    OperationDescriptor {
        id: OperationId::SystemShutdown,
        method: HttpMethod::Post,
        path: "/v1/system/shutdown",
        bindings: &[Binding::NormalUds, Binding::MaintenanceUds],
        authorization: Authorization::LocalOperatorOrStateOwnerPeer,
        request_codec: CodecId::JsonShutdownV1,
        response_codec: Some(CodecId::JsonShutdownAcceptedV1),
        idempotency: Idempotency::AddressedState,
        risk: Risk::SafetyControl,
        one_time_mode: None,
    },
];
