//! Generated atomic core behavior cases (RED suite, layer 2). DO NOT EDIT.
//!
//! Regenerated by `scripts/generate_red_core_cases.py` from
//! `specs/contract-cases.toml`; the committed bytes must equal the generator
//! output. Each function is one nextest-visible atomic case: it validates its
//! frozen fixture/oracle, starts the typed SUT path, records the registered
//! initial frontier, compares the real final observable, and writes a
//! `behavior_red` terminal until the implementation slice removes the gap.

#![allow(clippy::needless_borrow)]

use crate::harness::{CompareResult, Oracle, TestCaseError, case, decode_hex, hex, outcome};
use msgriver_core::Frontier;

const DIGEST_CORE_BV_ID_VALID_MAX: &str =
    "10ac20bee9e4bc6e4a4dee0295c55b8738968969e34eb09f1756617c5cd4a97d";

const DIGEST_CORE_BV_ID_EMPTY: &str =
    "cfa78ebea7ae777e9abc2f3592c4146342796978b81ab189e50d5d314021a598";

const DIGEST_CORE_BV_ID_LEN129: &str =
    "4e87ec8f523306b0dd52a2707b82ed301a06f590a49b2c84735016d777728cc6";

const DIGEST_CORE_BV_ID_LEADDOT: &str =
    "a0d9daa279aba8d702f00217dec7ca3c1b7e89277c66d86605b3d5cde19ede2d";

const DIGEST_CORE_BV_ID_NONASCII: &str =
    "25f4c173ecf9cb076f230a1d7b8ded7222d406abbea645e1e3119ecf073b7e10";

const DIGEST_CORE_BV_TOPIC_VALID64: &str =
    "a1d1b94e269a5f6e114964e10759c44610668e90ad3e3ff30b20a2893e4364e2";

const DIGEST_CORE_BV_TOPIC_LEN65: &str =
    "85994be116fe6b0f836580f0a12972930092200ddc7bd73d2988efad1e15964a";

const DIGEST_CORE_BV_TOPIC_SLASH: &str =
    "f0f150e0ec217e1093ad6262c8d9e12aee61d8d595a9c43bd8dbb98c286d3c8f";

const DIGEST_CORE_BV_TAGS_COUNT9: &str =
    "e492f607bdaaf0c31fd3eaef555a5f6df6d29ee6331246f1451839ff89c3d7c3";

const DIGEST_CORE_BV_TEXT_BADUTF8: &str =
    "28152dd218071403a2107d4bc165092562fdeb4533812d4bb1a7b9a62edd90e9";

const DIGEST_CORE_BV_TEXT_TITLE257: &str =
    "d0b8bb5d7d1d8b486f626ae33e18e3e40a264ed5efbc4ad55a10e8d6d774021d";

const DIGEST_CORE_BV_EXPIRY_PAST: &str =
    "13b5c78299805abc843ce90161210d6cdcb0c8fa18538c567caf9f5e32b4a53e";

const DIGEST_CORE_MATH_UTC_ADD: &str =
    "45a876181689657d366c89a4496be594c2cf148245bfca3591717329168d6eda";

const DIGEST_CORE_MATH_UTC_OVERFLOW: &str =
    "2ab7f955806b1c2a52d255a89c3cf5b400bd2f767f2c9c079076ef35d06f75a3";

const DIGEST_CORE_MATH_JITTER: &str =
    "531ec271b713456e5d4781ecb36311e37648bc9c797c43b981d6f86fea499d17";

const DIGEST_CORE_MATH_CAP_FIT: &str =
    "900c42bc6cfb4be27cbfb97073d8fdde84c48ba153b018384804134d23aebb6e";

const DIGEST_CORE_MATH_CAP_OVER: &str =
    "9266d1c670bb9904caf763b82350cac48953c0fb3006ce93b7c278b0568bf3b8";

const DIGEST_CORE_CANON_REQUEST: &str =
    "e84b1fd9257715cd269237372d8e1dae6615637a0d31637b1e64a52c58bec5d8";

const DIGEST_CORE_CANON_TAG_SORT: &str =
    "903c6d1032fb6a73656c7cbacbf9aea0ed92edf5ae9dfb3ae35418766dbb0c52";

const DIGEST_CORE_MAC_FINGERPRINT: &str =
    "b0215cf5bcb6bc8e5e86975b4242615c1ef699972d6bbc71b479da23d9b62292";

const DIGEST_CORE_MAC_KEYVERSION: &str =
    "6055d09d31bae50579b4895f653415f5021ca175b6e8e50b48f5e164fe35e9cc";

const DIGEST_CORE_MAC_LOOKUP_DOMAIN: &str =
    "0e8d98468359079e9076d0e21b8a1a5f0eb563314bb3107ef2edcc61a7e84606";

const DIGEST_CORE_BACKOFF_ATTEMPT1: &str =
    "ab2ea915e5f6ca4e3726a777a77fb3f152aeecd0751806c24cc23b1054aa5e4a";

const DIGEST_CORE_BACKOFF_SATURATE: &str =
    "9963017becb2b4f334ee65a2edf8746c18e9d3ac120dfd6e3474470f57077d49";

const DIGEST_CORE_BACKOFF_RETRYAFTER_MAX: &str =
    "7218358c37c643cadbab3c56196b431af37d3228f70c231bfbef2f9a49e114be";

const DIGEST_CORE_BACKOFF_RETRYAFTER_CLAMP: &str =
    "b56d319171dd4e2d4b4e16501e1093b1681d81d58e39f43bd9d0ce16704c1c28";

const DIGEST_CORE_STATE_TRANSITION_VALID: &str =
    "359c11ffaa82fcccaf88ce647256567f2ecacae79ebcdbe3aae253c9b3f6504c";

const DIGEST_CORE_STATE_TRANSITION_INVALID: &str =
    "699b71d5da70815596bf07f37c38b26ec037a0a459f906957eff88ac1d41b14e";

const DIGEST_CORE_STATE_STICKY_EFFECT: &str =
    "ace3cfdcffb99d4b148490fb1d7dc2a31b71700a349c55d8d5850d6348a3fd66";

const DIGEST_CORE_STATE_CANCEL_DELIVERING: &str =
    "9f83252ae91789049b408c34b9261fe00478258f2a3eb0faa4a3a8a8b2525591";

const DIGEST_CORE_PREC_ACCEPT_WINS: &str =
    "5ba9ac68222b2f93d095219399c5617a2fb205e4a8140c85d5feca27dd87b8ef";

const DIGEST_CORE_PREC_CANCEL_OVER_EXPIRY: &str =
    "6e0e6f69200a45a6773370ca2d6bbe1ac049efa6f7ee3f41153bd6d19ca20e24";

const DIGEST_CORE_PREC_EXPIRY_OVER_EXHAUST: &str =
    "d9eefa8a28e6b62706ab7673e1e32f692b0a59fc3861cebf97f61cdedeb16f58";

const DIGEST_CORE_PREC_EXHAUST_FAILED: &str =
    "bb1efb07779ae8fb255730d2d8e31e7652041c0f55c4f2f4ceb5277b9db18858";

const DIGEST_CORE_PREC_TERMINAL_NOOP: &str =
    "8bc13ef95d6dbafacb10967216d44a654e8d61b9ecd6c7db0b81294b83803e43";

const DIGEST_CORE_PREC_LATE_ACK_PROMOTE: &str =
    "9dc2cab7f770f6965d513807d5d5547880ea2d3a44eb15f609b582b426441a62";

const DIGEST_CORE_FENCE_MATCH: &str =
    "adcade366c70c802dbb0aaae843ef8f142bd791e880e504509f458ac2f58adfa";

const DIGEST_CORE_FENCE_STALE: &str =
    "0506f19a7c1531327abd138893aae3c07cd52c644795e6ea3ad47bc38b0933fe";

const DIGEST_CORE_FENCE_AMBIGUITY_OR: &str =
    "fc63c12b6f07fb6ec116c12eb56b0ae6eadb10ee99632d1be91335796b618f30";

const DIGEST_CORE_FENCE_LEASE_CONFIG: &str =
    "b7820ed9c3281deff342dcc1736f7c3d300d17f478b435425332f90ed538e706";

const DIGEST_CORE_SAFETIME_MAX: &str =
    "f125a15f4d8975736b00acc615787a7dcd3e2452052a2cedb031ae57267dc644";

const DIGEST_CORE_SAFETIME_MONOTONIC: &str =
    "ee1c30fdbaaf776fe97976ca9fe01f3c1494e798460e3c4749a1e854d24b140d";

const DIGEST_CORE_SAFETIME_PROVEN_EXPIRED: &str =
    "762b3fe6f4eb8cb23ea3ccd0ce823328fef4fe623159cb40109ccbdaf0d65769";

const DIGEST_CORE_SAFETIME_CLOCK_THRESHOLD: &str =
    "def176935a21d1718b6dc46ce26362c6064c67bae77a315884cca7bb2bb5390f";

const DIGEST_CORE_GEN_INCREMENT: &str =
    "7012907203594f539d333d52463aa4c5751b7d0631f6981c64bec137c4fd684f";

const DIGEST_CORE_GEN_EXHAUST: &str =
    "8972152eca2d8ca7c063774ec870ed75c011dcc824acd124bac1c96490d38c2d";

const DIGEST_CORE_GEN_LIMBS: &str =
    "1128f722c9c8e8437e857ab65332ff4438f42992a99883108741c7bbfe0bd681";

const DIGEST_CORE_INCARN_WIRE: &str =
    "25b579b983fc0e0cd93794def20993f17ad35c6a689f2fdad8d0bf4a4066da5d";

const DIGEST_CORE_INCARN_SERIAL_EXHAUST: &str =
    "a30326aaac0665fd7c95fdd816b74bf32fdea31bd8eeb20eab27ed00ae5d1314";

const DIGEST_CORE_INCARN_SERIAL_BURN: &str =
    "07952e95761df086f1552b85b34e7612301a48eae53b2605b8140b4e30f99757";

const DIGEST_CORE_RING_SERIAL_NEXT: &str =
    "20ba17ee42d16aee2fcf23c0ec0cb3dd9c0bff688729158db29e87b70fdfd60d";

const DIGEST_CORE_READY_BOTH_EXHAUSTED: &str =
    "43fe634d8f3aacd1d64a3a0df0c71cde71f8d01a1e80503975d22d2d5141049f";

const DIGEST_CORE_RING_SERIAL_EXHAUSTED: &str =
    "1256987913cf557af881b8c99846d0efdf305dc4d1edf2034dfe10459a0145c3";

fn readiness_label(reason: msgriver_core::incarnation::ReadinessReason) -> &'static str {
    use msgriver_core::incarnation::ReadinessReason;
    match reason {
        ReadinessReason::GenerationExhausted => "generation_exhausted",
        ReadinessReason::IncarnationExhausted => "incarnation_exhausted",
    }
}

fn parse_state(s: &str) -> Result<msgriver_core::state::MessageState, TestCaseError> {
    use msgriver_core::state::MessageState;
    Ok(match s {
        "queued" => MessageState::Queued,
        "held" => MessageState::Held,
        "delivering" => MessageState::Delivering,
        "retry_scheduled" => MessageState::RetryScheduled,
        "provider_accepted" => MessageState::ProviderAccepted,
        "failed" => MessageState::Failed,
        "cancelled" => MessageState::Cancelled,
        "expired" => MessageState::Expired,
        other => return Err(TestCaseError::Parse(format!("unknown state {other:?}"))),
    })
}

fn parse_event(s: &str) -> Result<msgriver_core::state::TransitionEvent, TestCaseError> {
    use msgriver_core::state::TransitionEvent;
    Ok(match s {
        "fair_claim" => TransitionEvent::FairClaim,
        "dispatch_mark" => TransitionEvent::DispatchMark,
        "transient_outcome" => TransitionEvent::TransientOutcome,
        "ambiguous_outcome" => TransitionEvent::AmbiguousOutcome,
        "cancel" => TransitionEvent::Cancel,
        other => return Err(TestCaseError::Parse(format!("unknown event {other:?}"))),
    })
}

fn parse_outcome(s: &str) -> Result<msgriver_core::fence::FenceOutcome, TestCaseError> {
    use msgriver_core::fence::FenceOutcome;
    Ok(match s {
        "accepted" => FenceOutcome::Accepted,
        "transient" => FenceOutcome::Transient,
        "permanent" => FenceOutcome::Permanent,
        "ambiguous" => FenceOutcome::Ambiguous,
        other => return Err(TestCaseError::Parse(format!("unknown outcome {other:?}"))),
    })
}

fn parse_winner(s: &str) -> msgriver_core::state::TerminalWinner {
    use msgriver_core::state::TerminalWinner;
    match s {
        "provider_accepted" => TerminalWinner::ProviderAccepted,
        "cancelled" => TerminalWinner::Cancelled,
        "expired" => TerminalWinner::Expired,
        "failed" => TerminalWinner::Failed,
        _ => TerminalWinner::NoTerminal,
    }
}

fn state_matches(r: &msgriver_core::state::TransitionResult, o: &Oracle) -> bool {
    use msgriver_core::state::MessageState;
    let want_state = match o.req("expect_state").unwrap_or("") {
        "queued" => MessageState::Queued,
        "held" => MessageState::Held,
        "delivering" => MessageState::Delivering,
        "retry_scheduled" => MessageState::RetryScheduled,
        "provider_accepted" => MessageState::ProviderAccepted,
        "failed" => MessageState::Failed,
        "cancelled" => MessageState::Cancelled,
        "expired" => MessageState::Expired,
        _ => return false,
    };
    r.state == want_state
        && r.flags.cancel_requested == o.bool("expect_cancel_requested").unwrap_or(false)
        && r.flags.effect_may_have_occurred == o.bool("expect_effect").unwrap_or(false)
        && r.flags.duplicate_effect_possible == o.bool("expect_duplicate").unwrap_or(false)
}

fn arbitration_matches(a: &msgriver_core::fence::FenceArbitration, o: &Oracle) -> bool {
    use msgriver_core::fence::{FenceArbitration, FenceOutcome};
    match (a, o.req("expect_arbitration").unwrap_or("")) {
        (FenceArbitration::Applied { outcome }, "applied") => {
            let want = o.req("expect_outcome").unwrap_or("");
            matches!(
                (outcome, want),
                (FenceOutcome::Accepted, "accepted")
                    | (FenceOutcome::Transient, "transient")
                    | (FenceOutcome::Permanent, "permanent")
                    | (FenceOutcome::Ambiguous, "ambiguous")
            )
        }
        (
            FenceArbitration::Stale {
                ambiguity_orred,
                attempt_delta,
            },
            "stale",
        ) => {
            *ambiguity_orred == o.bool("expect_ambiguity_orred").unwrap_or(false)
                && *attempt_delta == o.u32("expect_attempt_delta").unwrap_or(0)
        }
        _ => false,
    }
}

fn optional_millis(o: &Oracle, key: &str) -> Result<Option<i64>, TestCaseError> {
    match o.req(key)? {
        "absent" => Ok(None),
        other => other
            .parse::<i64>()
            .map(Some)
            .map_err(|e| TestCaseError::Parse(format!("{key}: {e}"))),
    }
}

fn build_canonical_input(
    o: &Oracle,
) -> Result<msgriver_core::canon::CanonicalInput, TestCaseError> {
    let options_present = matches!(o.req("options"), Ok("present"));
    Ok(msgriver_core::canon::CanonicalInput {
        provider: o.req("provider")?.as_bytes().to_vec(),
        destination_kind: o.req("dest_kind")?.as_bytes().to_vec(),
        destination_schema_version: o.u32("dest_schema")?,
        destination_fields: o
            .list("dest_fields")?
            .into_iter()
            .map(String::into_bytes)
            .collect(),
        content_kind: o.req("content_kind")?.as_bytes().to_vec(),
        content_schema_version: o.u32("content_schema")?,
        content_fields: o
            .list("content_fields")?
            .into_iter()
            .map(String::into_bytes)
            .collect(),
        options_kind: if options_present {
            Some(o.req("options_kind")?.as_bytes().to_vec())
        } else {
            None
        },
        options_schema_version: if options_present {
            Some(o.u32("options_schema")?)
        } else {
            None
        },
        options_fields: if options_present {
            o.list("options_fields")?
                .into_iter()
                .map(String::into_bytes)
                .collect()
        } else {
            Vec::new()
        },
        options_set_like: o.bool("options_set_like").unwrap_or(false),
        expires_at_millis: optional_millis(o, "expires")?,
        correlation_id: match o.req("correlation")? {
            "absent" => None,
            other => Some(other.as_bytes().to_vec()),
        },
    })
}

#[test]
fn core_bv_id_valid_max() -> Result<(), TestCaseError> {
    case(
        "CORE-BV-ID-VALID-MAX",
        "tests/fixtures/oracles/core/core-bv-id-valid-max.txt",
        DIGEST_CORE_BV_ID_VALID_MAX,
        Frontier::ValidateBoundedGrammar,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let input = o.raw_bytes("input")?;
            outcome(msgriver_core::bounded::check_identifier(input), o, |()| {
                true
            })
        },
    )
}

#[test]
fn core_bv_id_empty() -> Result<(), TestCaseError> {
    case(
        "CORE-BV-ID-EMPTY",
        "tests/fixtures/oracles/core/core-bv-id-empty.txt",
        DIGEST_CORE_BV_ID_EMPTY,
        Frontier::ValidateBoundedGrammar,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let input = o.raw_bytes("input")?;
            outcome(msgriver_core::bounded::check_identifier(input), o, |()| {
                true
            })
        },
    )
}

#[test]
fn core_bv_id_len129() -> Result<(), TestCaseError> {
    case(
        "CORE-BV-ID-LEN129",
        "tests/fixtures/oracles/core/core-bv-id-len129.txt",
        DIGEST_CORE_BV_ID_LEN129,
        Frontier::ValidateBoundedGrammar,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let input = o.raw_bytes("input")?;
            outcome(msgriver_core::bounded::check_identifier(input), o, |()| {
                true
            })
        },
    )
}

#[test]
fn core_bv_id_leaddot() -> Result<(), TestCaseError> {
    case(
        "CORE-BV-ID-LEADDOT",
        "tests/fixtures/oracles/core/core-bv-id-leaddot.txt",
        DIGEST_CORE_BV_ID_LEADDOT,
        Frontier::ValidateBoundedGrammar,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let input = o.raw_bytes("input")?;
            outcome(msgriver_core::bounded::check_identifier(input), o, |()| {
                true
            })
        },
    )
}

#[test]
fn core_bv_id_nonascii() -> Result<(), TestCaseError> {
    case(
        "CORE-BV-ID-NONASCII",
        "tests/fixtures/oracles/core/core-bv-id-nonascii.txt",
        DIGEST_CORE_BV_ID_NONASCII,
        Frontier::ValidateBoundedGrammar,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let input = o.raw_bytes("input")?;
            outcome(msgriver_core::bounded::check_identifier(input), o, |()| {
                true
            })
        },
    )
}

#[test]
fn core_bv_topic_valid64() -> Result<(), TestCaseError> {
    case(
        "CORE-BV-TOPIC-VALID64",
        "tests/fixtures/oracles/core/core-bv-topic-valid64.txt",
        DIGEST_CORE_BV_TOPIC_VALID64,
        Frontier::ValidateBoundedGrammar,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let input = o.raw_bytes("input")?;
            outcome(msgriver_core::bounded::check_ntfy_topic(input), o, |()| {
                true
            })
        },
    )
}

#[test]
fn core_bv_topic_len65() -> Result<(), TestCaseError> {
    case(
        "CORE-BV-TOPIC-LEN65",
        "tests/fixtures/oracles/core/core-bv-topic-len65.txt",
        DIGEST_CORE_BV_TOPIC_LEN65,
        Frontier::ValidateBoundedGrammar,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let input = o.raw_bytes("input")?;
            outcome(msgriver_core::bounded::check_ntfy_topic(input), o, |()| {
                true
            })
        },
    )
}

#[test]
fn core_bv_topic_slash() -> Result<(), TestCaseError> {
    case(
        "CORE-BV-TOPIC-SLASH",
        "tests/fixtures/oracles/core/core-bv-topic-slash.txt",
        DIGEST_CORE_BV_TOPIC_SLASH,
        Frontier::ValidateBoundedGrammar,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let input = o.raw_bytes("input")?;
            outcome(msgriver_core::bounded::check_ntfy_topic(input), o, |()| {
                true
            })
        },
    )
}

#[test]
fn core_bv_tags_count9() -> Result<(), TestCaseError> {
    case(
        "CORE-BV-TAGS-COUNT9",
        "tests/fixtures/oracles/core/core-bv-tags-count9.txt",
        DIGEST_CORE_BV_TAGS_COUNT9,
        Frontier::ValidateBoundedGrammar,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let list = o.list("tags")?;
            let tags: Vec<&[u8]> = list.iter().map(String::as_bytes).collect();
            outcome(msgriver_core::bounded::check_ntfy_tags(&tags), o, |()| true)
        },
    )
}

#[test]
fn core_bv_text_badutf8() -> Result<(), TestCaseError> {
    case(
        "CORE-BV-TEXT-BADUTF8",
        "tests/fixtures/oracles/core/core-bv-text-badutf8.txt",
        DIGEST_CORE_BV_TEXT_BADUTF8,
        Frontier::ValidateBoundedGrammar,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let text = match o.opt("text_hex") {
                Some(h) => decode_hex(h)?,
                None => o.raw_bytes("text")?.to_vec(),
            };
            let title = o.opt("title").map(str::as_bytes);
            outcome(
                msgriver_core::bounded::check_text_content(
                    &text,
                    title,
                    o.u32("text_limit")?,
                    o.u32("title_limit")?,
                ),
                o,
                |()| true,
            )
        },
    )
}

#[test]
fn core_bv_text_title257() -> Result<(), TestCaseError> {
    case(
        "CORE-BV-TEXT-TITLE257",
        "tests/fixtures/oracles/core/core-bv-text-title257.txt",
        DIGEST_CORE_BV_TEXT_TITLE257,
        Frontier::ValidateBoundedGrammar,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let text = match o.opt("text_hex") {
                Some(h) => decode_hex(h)?,
                None => o.raw_bytes("text")?.to_vec(),
            };
            let title = o.opt("title").map(str::as_bytes);
            outcome(
                msgriver_core::bounded::check_text_content(
                    &text,
                    title,
                    o.u32("text_limit")?,
                    o.u32("title_limit")?,
                ),
                o,
                |()| true,
            )
        },
    )
}

#[test]
fn core_bv_expiry_past() -> Result<(), TestCaseError> {
    case(
        "CORE-BV-EXPIRY-PAST",
        "tests/fixtures/oracles/core/core-bv-expiry-past.txt",
        DIGEST_CORE_BV_EXPIRY_PAST,
        Frontier::ValidateBoundedGrammar,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            outcome(
                msgriver_core::bounded::check_expiry_boundary(o.i64("now")?, o.i64("expires")?),
                o,
                |()| true,
            )
        },
    )
}

#[test]
fn core_math_utc_add() -> Result<(), TestCaseError> {
    case(
        "CORE-MATH-UTC-ADD",
        "tests/fixtures/oracles/core/core-math-utc-add.txt",
        DIGEST_CORE_MATH_UTC_ADD,
        Frontier::CheckedArithmetic,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            outcome(
                msgriver_core::math::utc_add_millis(o.i64("base")?, o.i64("delta")?),
                o,
                |v| *v == o.i64("expect_value").unwrap_or(0),
            )
        },
    )
}

#[test]
fn core_math_utc_overflow() -> Result<(), TestCaseError> {
    case(
        "CORE-MATH-UTC-OVERFLOW",
        "tests/fixtures/oracles/core/core-math-utc-overflow.txt",
        DIGEST_CORE_MATH_UTC_OVERFLOW,
        Frontier::CheckedArithmetic,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            outcome(
                msgriver_core::math::utc_add_millis(o.i64("base")?, o.i64("delta")?),
                o,
                |v| *v == o.i64("expect_value").unwrap_or(0),
            )
        },
    )
}

#[test]
fn core_math_jitter() -> Result<(), TestCaseError> {
    case(
        "CORE-MATH-JITTER",
        "tests/fixtures/oracles/core/core-math-jitter.txt",
        DIGEST_CORE_MATH_JITTER,
        Frontier::CheckedArithmetic,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let seed = o.hex_bytes("seed_hex")?;
            let mut s = [0u8; 32];
            s.copy_from_slice(&seed);
            outcome(msgriver_core::math::jitter_multiplier(&s), o, |j| {
                j.0 as i64 == o.i64("expect_value").unwrap_or(0)
            })
        },
    )
}

#[test]
fn core_math_cap_fit() -> Result<(), TestCaseError> {
    case(
        "CORE-MATH-CAP-FIT",
        "tests/fixtures/oracles/core/core-math-cap-fit.txt",
        DIGEST_CORE_MATH_CAP_FIT,
        Frontier::CheckedArithmetic,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            outcome(
                msgriver_core::math::checkpoint_capacity_fits(o.u64("bytes")?, o.u32("entries")?),
                o,
                |()| true,
            )
        },
    )
}

#[test]
fn core_math_cap_over() -> Result<(), TestCaseError> {
    case(
        "CORE-MATH-CAP-OVER",
        "tests/fixtures/oracles/core/core-math-cap-over.txt",
        DIGEST_CORE_MATH_CAP_OVER,
        Frontier::CheckedArithmetic,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            outcome(
                msgriver_core::math::checkpoint_capacity_fits(o.u64("bytes")?, o.u32("entries")?),
                o,
                |()| true,
            )
        },
    )
}

#[test]
fn core_canon_request() -> Result<(), TestCaseError> {
    case(
        "CORE-CANON-REQUEST",
        "tests/fixtures/oracles/core/core-canon-request.txt",
        DIGEST_CORE_CANON_REQUEST,
        Frontier::CanonicalEncode,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let input = build_canonical_input(o)?;
            outcome(
                msgriver_core::canon::canonical_request_v1(&input),
                o,
                |bytes| hex(bytes) == o.req("expect_canonical_hex").unwrap_or(""),
            )
        },
    )
}

#[test]
fn core_canon_tag_sort() -> Result<(), TestCaseError> {
    case(
        "CORE-CANON-TAG-SORT",
        "tests/fixtures/oracles/core/core-canon-tag-sort.txt",
        DIGEST_CORE_CANON_TAG_SORT,
        Frontier::CanonicalEncode,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let input = build_canonical_input(o)?;
            outcome(
                msgriver_core::canon::canonical_request_v1(&input),
                o,
                |bytes| hex(bytes) == o.req("expect_canonical_hex").unwrap_or(""),
            )
        },
    )
}

#[test]
fn core_mac_fingerprint() -> Result<(), TestCaseError> {
    case(
        "CORE-MAC-FINGERPRINT",
        "tests/fixtures/oracles/core/core-mac-fingerprint.txt",
        DIGEST_CORE_MAC_FINGERPRINT,
        Frontier::MacDomainSeparate,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let canon = o.hex_bytes("canonical_hex")?;
            let key = o.hex_bytes("mac_key_hex")?;
            let kv = o.u32("key_version")?;
            outcome(
                msgriver_core::canon::semantic_fingerprint_v1(&canon, &key, kv),
                o,
                |(v, tag)| *v == kv && hex(&tag.0) == o.req("expect_tag_hex").unwrap_or(""),
            )
        },
    )
}

#[test]
fn core_mac_keyversion() -> Result<(), TestCaseError> {
    case(
        "CORE-MAC-KEYVERSION",
        "tests/fixtures/oracles/core/core-mac-keyversion.txt",
        DIGEST_CORE_MAC_KEYVERSION,
        Frontier::MacDomainSeparate,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let canon = o.hex_bytes("canonical_hex")?;
            let key = o.hex_bytes("mac_key_hex")?;
            let kv = o.u32("key_version")?;
            outcome(
                msgriver_core::canon::semantic_fingerprint_v1(&canon, &key, kv),
                o,
                |(v, tag)| *v == kv && hex(&tag.0) == o.req("expect_tag_hex").unwrap_or(""),
            )
        },
    )
}

#[test]
fn core_mac_lookup_domain() -> Result<(), TestCaseError> {
    case(
        "CORE-MAC-LOOKUP-DOMAIN",
        "tests/fixtures/oracles/core/core-mac-lookup-domain.txt",
        DIGEST_CORE_MAC_LOOKUP_DOMAIN,
        Frontier::MacDomainSeparate,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let principal = o.raw_bytes("principal")?;
            let key = o.raw_bytes("key")?;
            let mackey = o.hex_bytes("mac_key_hex")?;
            let kv = o.u32("key_version")?;
            outcome(
                msgriver_core::canon::lookup_digest_v1(principal, key, &mackey, kv),
                o,
                |(v, tag)| *v == kv && hex(&tag.0) == o.req("expect_tag_hex").unwrap_or(""),
            )
        },
    )
}

#[test]
fn core_backoff_attempt1() -> Result<(), TestCaseError> {
    case(
        "CORE-BACKOFF-ATTEMPT1",
        "tests/fixtures/oracles/core/core-backoff-attempt1.txt",
        DIGEST_CORE_BACKOFF_ATTEMPT1,
        Frontier::ComputeBackoff,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            outcome(
                msgriver_core::retry::backoff(
                    o.u64("base")?,
                    o.u32("factor")?,
                    o.u64("max")?,
                    o.u32("attempt")?,
                    o.u32("jitter")?,
                ),
                o,
                |v| *v == o.u64("expect_value").unwrap_or(0),
            )
        },
    )
}

#[test]
fn core_backoff_saturate() -> Result<(), TestCaseError> {
    case(
        "CORE-BACKOFF-SATURATE",
        "tests/fixtures/oracles/core/core-backoff-saturate.txt",
        DIGEST_CORE_BACKOFF_SATURATE,
        Frontier::ComputeBackoff,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            outcome(
                msgriver_core::retry::backoff(
                    o.u64("base")?,
                    o.u32("factor")?,
                    o.u64("max")?,
                    o.u32("attempt")?,
                    o.u32("jitter")?,
                ),
                o,
                |v| *v == o.u64("expect_value").unwrap_or(0),
            )
        },
    )
}

#[test]
fn core_backoff_retryafter_max() -> Result<(), TestCaseError> {
    case(
        "CORE-BACKOFF-RETRYAFTER-MAX",
        "tests/fixtures/oracles/core/core-backoff-retryafter-max.txt",
        DIGEST_CORE_BACKOFF_RETRYAFTER_MAX,
        Frontier::ComputeBackoff,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            outcome(
                msgriver_core::retry::combine_retry_after(o.u64("backoff")?, o.u64("retry_after")?),
                o,
                |v| *v == o.u64("expect_value").unwrap_or(0),
            )
        },
    )
}

#[test]
fn core_backoff_retryafter_clamp() -> Result<(), TestCaseError> {
    case(
        "CORE-BACKOFF-RETRYAFTER-CLAMP",
        "tests/fixtures/oracles/core/core-backoff-retryafter-clamp.txt",
        DIGEST_CORE_BACKOFF_RETRYAFTER_CLAMP,
        Frontier::ComputeBackoff,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            outcome(
                msgriver_core::retry::combine_retry_after(o.u64("backoff")?, o.u64("retry_after")?),
                o,
                |v| *v == o.u64("expect_value").unwrap_or(0),
            )
        },
    )
}

#[test]
fn core_state_transition_valid() -> Result<(), TestCaseError> {
    case(
        "CORE-STATE-TRANSITION-VALID",
        "tests/fixtures/oracles/core/core-state-transition-valid.txt",
        DIGEST_CORE_STATE_TRANSITION_VALID,
        Frontier::StateTransition,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let from = parse_state(o.req("from")?)?;
            let flags = msgriver_core::state::StickyFlags {
                cancel_requested: o.bool("cancel_requested")?,
                effect_may_have_occurred: o.bool("effect")?,
                duplicate_effect_possible: o.bool("duplicate")?,
            };
            let event = parse_event(o.req("event")?)?;
            outcome(
                msgriver_core::state::transition(from, flags, event),
                o,
                |r| state_matches(r, o),
            )
        },
    )
}

#[test]
fn core_state_transition_invalid() -> Result<(), TestCaseError> {
    case(
        "CORE-STATE-TRANSITION-INVALID",
        "tests/fixtures/oracles/core/core-state-transition-invalid.txt",
        DIGEST_CORE_STATE_TRANSITION_INVALID,
        Frontier::StateTransition,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let from = parse_state(o.req("from")?)?;
            let flags = msgriver_core::state::StickyFlags {
                cancel_requested: o.bool("cancel_requested")?,
                effect_may_have_occurred: o.bool("effect")?,
                duplicate_effect_possible: o.bool("duplicate")?,
            };
            let event = parse_event(o.req("event")?)?;
            outcome(
                msgriver_core::state::transition(from, flags, event),
                o,
                |r| state_matches(r, o),
            )
        },
    )
}

#[test]
fn core_state_sticky_effect() -> Result<(), TestCaseError> {
    case(
        "CORE-STATE-STICKY-EFFECT",
        "tests/fixtures/oracles/core/core-state-sticky-effect.txt",
        DIGEST_CORE_STATE_STICKY_EFFECT,
        Frontier::StateTransition,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let from = parse_state(o.req("from")?)?;
            let flags = msgriver_core::state::StickyFlags {
                cancel_requested: o.bool("cancel_requested")?,
                effect_may_have_occurred: o.bool("effect")?,
                duplicate_effect_possible: o.bool("duplicate")?,
            };
            let event = parse_event(o.req("event")?)?;
            outcome(
                msgriver_core::state::transition(from, flags, event),
                o,
                |r| state_matches(r, o),
            )
        },
    )
}

#[test]
fn core_state_cancel_delivering() -> Result<(), TestCaseError> {
    case(
        "CORE-STATE-CANCEL-DELIVERING",
        "tests/fixtures/oracles/core/core-state-cancel-delivering.txt",
        DIGEST_CORE_STATE_CANCEL_DELIVERING,
        Frontier::StateTransition,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let from = parse_state(o.req("from")?)?;
            let flags = msgriver_core::state::StickyFlags {
                cancel_requested: o.bool("cancel_requested")?,
                effect_may_have_occurred: o.bool("effect")?,
                duplicate_effect_possible: o.bool("duplicate")?,
            };
            let event = parse_event(o.req("event")?)?;
            outcome(
                msgriver_core::state::transition(from, flags, event),
                o,
                |r| state_matches(r, o),
            )
        },
    )
}

#[test]
fn core_prec_accept_wins() -> Result<(), TestCaseError> {
    case(
        "CORE-PREC-ACCEPT-WINS",
        "tests/fixtures/oracles/core/core-prec-accept-wins.txt",
        DIGEST_CORE_PREC_ACCEPT_WINS,
        Frontier::TerminalPrecedence,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let guards = msgriver_core::state::TerminalGuards {
                known_provider_acceptance: o.bool("known_acceptance")?,
                cancel_committed: o.bool("cancel_committed")?,
                expiry_eligible: o.bool("expiry_eligible")?,
                attempt_exhausted: o.bool("attempt_exhausted")?,
                late_verifiable_ack: o.bool("late_verifiable_ack")?,
            };
            outcome(msgriver_core::state::terminal_precedence(guards), o, |w| {
                let want = o.req("expect_winner").unwrap_or("");
                *w == parse_winner(want)
            })
        },
    )
}

#[test]
fn core_prec_cancel_over_expiry() -> Result<(), TestCaseError> {
    case(
        "CORE-PREC-CANCEL-OVER-EXPIRY",
        "tests/fixtures/oracles/core/core-prec-cancel-over-expiry.txt",
        DIGEST_CORE_PREC_CANCEL_OVER_EXPIRY,
        Frontier::TerminalPrecedence,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let guards = msgriver_core::state::TerminalGuards {
                known_provider_acceptance: o.bool("known_acceptance")?,
                cancel_committed: o.bool("cancel_committed")?,
                expiry_eligible: o.bool("expiry_eligible")?,
                attempt_exhausted: o.bool("attempt_exhausted")?,
                late_verifiable_ack: o.bool("late_verifiable_ack")?,
            };
            outcome(msgriver_core::state::terminal_precedence(guards), o, |w| {
                let want = o.req("expect_winner").unwrap_or("");
                *w == parse_winner(want)
            })
        },
    )
}

#[test]
fn core_prec_expiry_over_exhaust() -> Result<(), TestCaseError> {
    case(
        "CORE-PREC-EXPIRY-OVER-EXHAUST",
        "tests/fixtures/oracles/core/core-prec-expiry-over-exhaust.txt",
        DIGEST_CORE_PREC_EXPIRY_OVER_EXHAUST,
        Frontier::TerminalPrecedence,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let guards = msgriver_core::state::TerminalGuards {
                known_provider_acceptance: o.bool("known_acceptance")?,
                cancel_committed: o.bool("cancel_committed")?,
                expiry_eligible: o.bool("expiry_eligible")?,
                attempt_exhausted: o.bool("attempt_exhausted")?,
                late_verifiable_ack: o.bool("late_verifiable_ack")?,
            };
            outcome(msgriver_core::state::terminal_precedence(guards), o, |w| {
                let want = o.req("expect_winner").unwrap_or("");
                *w == parse_winner(want)
            })
        },
    )
}

#[test]
fn core_prec_exhaust_failed() -> Result<(), TestCaseError> {
    case(
        "CORE-PREC-EXHAUST-FAILED",
        "tests/fixtures/oracles/core/core-prec-exhaust-failed.txt",
        DIGEST_CORE_PREC_EXHAUST_FAILED,
        Frontier::TerminalPrecedence,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let guards = msgriver_core::state::TerminalGuards {
                known_provider_acceptance: o.bool("known_acceptance")?,
                cancel_committed: o.bool("cancel_committed")?,
                expiry_eligible: o.bool("expiry_eligible")?,
                attempt_exhausted: o.bool("attempt_exhausted")?,
                late_verifiable_ack: o.bool("late_verifiable_ack")?,
            };
            outcome(msgriver_core::state::terminal_precedence(guards), o, |w| {
                let want = o.req("expect_winner").unwrap_or("");
                *w == parse_winner(want)
            })
        },
    )
}

#[test]
fn core_prec_terminal_noop() -> Result<(), TestCaseError> {
    case(
        "CORE-PREC-TERMINAL-NOOP",
        "tests/fixtures/oracles/core/core-prec-terminal-noop.txt",
        DIGEST_CORE_PREC_TERMINAL_NOOP,
        Frontier::TerminalPrecedence,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let guards = msgriver_core::state::TerminalGuards {
                known_provider_acceptance: o.bool("known_acceptance")?,
                cancel_committed: o.bool("cancel_committed")?,
                expiry_eligible: o.bool("expiry_eligible")?,
                attempt_exhausted: o.bool("attempt_exhausted")?,
                late_verifiable_ack: o.bool("late_verifiable_ack")?,
            };
            outcome(msgriver_core::state::terminal_precedence(guards), o, |w| {
                let want = o.req("expect_winner").unwrap_or("");
                *w == parse_winner(want)
            })
        },
    )
}

#[test]
fn core_prec_late_ack_promote() -> Result<(), TestCaseError> {
    case(
        "CORE-PREC-LATE-ACK-PROMOTE",
        "tests/fixtures/oracles/core/core-prec-late-ack-promote.txt",
        DIGEST_CORE_PREC_LATE_ACK_PROMOTE,
        Frontier::TerminalPrecedence,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let guards = msgriver_core::state::TerminalGuards {
                known_provider_acceptance: o.bool("known_acceptance")?,
                cancel_committed: o.bool("cancel_committed")?,
                expiry_eligible: o.bool("expiry_eligible")?,
                attempt_exhausted: o.bool("attempt_exhausted")?,
                late_verifiable_ack: o.bool("late_verifiable_ack")?,
            };
            outcome(msgriver_core::state::terminal_precedence(guards), o, |w| {
                let want = o.req("expect_winner").unwrap_or("");
                *w == parse_winner(want)
            })
        },
    )
}

#[test]
fn core_fence_match() -> Result<(), TestCaseError> {
    case(
        "CORE-FENCE-MATCH",
        "tests/fixtures/oracles/core/core-fence-match.txt",
        DIGEST_CORE_FENCE_MATCH,
        Frontier::FenceArbitrate,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let fence_outcome = parse_outcome(o.req("outcome")?)?;
            outcome(
                msgriver_core::fence::arbitrate_outcome(
                    o.u64("cur_lease")?,
                    o.u128("cur_fence")?,
                    o.u64("upd_lease")?,
                    o.u128("upd_fence")?,
                    fence_outcome,
                ),
                o,
                |a| arbitration_matches(a, o),
            )
        },
    )
}

#[test]
fn core_fence_stale() -> Result<(), TestCaseError> {
    case(
        "CORE-FENCE-STALE",
        "tests/fixtures/oracles/core/core-fence-stale.txt",
        DIGEST_CORE_FENCE_STALE,
        Frontier::FenceArbitrate,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let fence_outcome = parse_outcome(o.req("outcome")?)?;
            outcome(
                msgriver_core::fence::arbitrate_outcome(
                    o.u64("cur_lease")?,
                    o.u128("cur_fence")?,
                    o.u64("upd_lease")?,
                    o.u128("upd_fence")?,
                    fence_outcome,
                ),
                o,
                |a| arbitration_matches(a, o),
            )
        },
    )
}

#[test]
fn core_fence_ambiguity_or() -> Result<(), TestCaseError> {
    case(
        "CORE-FENCE-AMBIGUITY-OR",
        "tests/fixtures/oracles/core/core-fence-ambiguity-or.txt",
        DIGEST_CORE_FENCE_AMBIGUITY_OR,
        Frontier::FenceArbitrate,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let fence_outcome = parse_outcome(o.req("outcome")?)?;
            outcome(
                msgriver_core::fence::arbitrate_outcome(
                    o.u64("cur_lease")?,
                    o.u128("cur_fence")?,
                    o.u64("upd_lease")?,
                    o.u128("upd_fence")?,
                    fence_outcome,
                ),
                o,
                |a| arbitration_matches(a, o),
            )
        },
    )
}

#[test]
fn core_fence_lease_config() -> Result<(), TestCaseError> {
    case(
        "CORE-FENCE-LEASE-CONFIG",
        "tests/fixtures/oracles/core/core-fence-lease-config.txt",
        DIGEST_CORE_FENCE_LEASE_CONFIG,
        Frontier::FenceArbitrate,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            outcome(
                msgriver_core::fence::validate_lease_config(
                    o.u64("ttl")?,
                    o.u64("timeout")?,
                    o.u64("margin")?,
                ),
                o,
                |()| true,
            )
        },
    )
}

#[test]
fn core_safetime_max() -> Result<(), TestCaseError> {
    case(
        "CORE-SAFETIME-MAX",
        "tests/fixtures/oracles/core/core-safetime-max.txt",
        DIGEST_CORE_SAFETIME_MAX,
        Frontier::SafeTimeHighWater,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let selected = match o.opt("selected") {
                Some(s) => Some(
                    s.parse::<i64>()
                        .map_err(|e| TestCaseError::Parse(format!("selected: {e}")))?,
                ),
                None => None,
            };
            outcome(
                msgriver_core::safetime::effective_high_water(o.i64("fixed")?, selected),
                o,
                |v| *v == o.i64("expect_value").unwrap_or(0),
            )
        },
    )
}

#[test]
fn core_safetime_monotonic() -> Result<(), TestCaseError> {
    case(
        "CORE-SAFETIME-MONOTONIC",
        "tests/fixtures/oracles/core/core-safetime-monotonic.txt",
        DIGEST_CORE_SAFETIME_MONOTONIC,
        Frontier::SafeTimeHighWater,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            outcome(
                msgriver_core::safetime::advance_high_water(o.i64("current")?, o.i64("candidate")?),
                o,
                |v| *v == o.i64("expect_value").unwrap_or(0),
            )
        },
    )
}

#[test]
fn core_safetime_proven_expired() -> Result<(), TestCaseError> {
    case(
        "CORE-SAFETIME-PROVEN-EXPIRED",
        "tests/fixtures/oracles/core/core-safetime-proven-expired.txt",
        DIGEST_CORE_SAFETIME_PROVEN_EXPIRED,
        Frontier::SafeTimeHighWater,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            outcome(
                msgriver_core::safetime::proven_expired(o.i64("boundary")?, o.i64("high_water")?),
                o,
                |v| *v == o.bool("expect_value").unwrap_or(false),
            )
        },
    )
}

#[test]
fn core_safetime_clock_threshold() -> Result<(), TestCaseError> {
    case(
        "CORE-SAFETIME-CLOCK-THRESHOLD",
        "tests/fixtures/oracles/core/core-safetime-clock-threshold.txt",
        DIGEST_CORE_SAFETIME_CLOCK_THRESHOLD,
        Frontier::SafeTimeHighWater,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            outcome(
                msgriver_core::safetime::clock_step_holds(
                    o.i64("wall_delta")?,
                    o.i64("monotonic_delta")?,
                ),
                o,
                |v| *v == o.bool("expect_value").unwrap_or(false),
            )
        },
    )
}

#[test]
fn core_gen_increment() -> Result<(), TestCaseError> {
    case(
        "CORE-GEN-INCREMENT",
        "tests/fixtures/oracles/core/core-gen-increment.txt",
        DIGEST_CORE_GEN_INCREMENT,
        Frontier::GenerationArithmetic,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            outcome(
                msgriver_core::generation::increment_generation(o.u64("current")?),
                o,
                |v| *v == o.u64("expect_value").unwrap_or(0),
            )
        },
    )
}

#[test]
fn core_gen_exhaust() -> Result<(), TestCaseError> {
    case(
        "CORE-GEN-EXHAUST",
        "tests/fixtures/oracles/core/core-gen-exhaust.txt",
        DIGEST_CORE_GEN_EXHAUST,
        Frontier::GenerationArithmetic,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            outcome(
                msgriver_core::generation::increment_generation(o.u64("current")?),
                o,
                |v| *v == o.u64("expect_value").unwrap_or(0),
            )
        },
    )
}

#[test]
fn core_gen_limbs() -> Result<(), TestCaseError> {
    case(
        "CORE-GEN-LIMBS",
        "tests/fixtures/oracles/core/core-gen-limbs.txt",
        DIGEST_CORE_GEN_LIMBS,
        Frontier::GenerationArithmetic,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            outcome(
                msgriver_core::generation::split_limbs(o.u64("generation")?),
                o,
                |(hi, lo)| {
                    *hi == o.u32("expect_hi").unwrap_or(0) && *lo == o.u32("expect_lo").unwrap_or(0)
                },
            )
        },
    )
}

#[test]
fn core_incarn_wire() -> Result<(), TestCaseError> {
    case(
        "CORE-INCARN-WIRE",
        "tests/fixtures/oracles/core/core-incarn-wire.txt",
        DIGEST_CORE_INCARN_WIRE,
        Frontier::IncarnationAlloc,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let ns = o.hex_bytes("namespace_hex")?;
            let mut n = [0u8; 24];
            n.copy_from_slice(&ns);
            outcome(
                msgriver_core::generation::incarnation_wire(&n, o.u64("serial")?),
                o,
                |s| s.as_str() == o.req("expect_wire").unwrap_or(""),
            )
        },
    )
}

#[test]
fn core_incarn_serial_exhaust() -> Result<(), TestCaseError> {
    case(
        "CORE-INCARN-SERIAL-EXHAUST",
        "tests/fixtures/oracles/core/core-incarn-serial-exhaust.txt",
        DIGEST_CORE_INCARN_SERIAL_EXHAUST,
        Frontier::IncarnationAlloc,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            outcome(
                msgriver_core::generation::branch_serial_exhausted(o.u64("high_water")?),
                o,
                |v| *v == o.bool("expect_value").unwrap_or(false),
            )
        },
    )
}

#[test]
fn core_incarn_serial_burn() -> Result<(), TestCaseError> {
    case(
        "CORE-INCARN-SERIAL-BURN",
        "tests/fixtures/oracles/core/core-incarn-serial-burn.txt",
        DIGEST_CORE_INCARN_SERIAL_BURN,
        Frontier::IncarnationAlloc,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            outcome(
                msgriver_core::generation::allocate_branch_serial(o.u64("high_water")?),
                o,
                |v| *v == o.u64("expect_value").unwrap_or(0),
            )
        },
    )
}

#[test]
fn core_ring_serial_next() -> Result<(), TestCaseError> {
    case(
        "CORE-RING-SERIAL-NEXT",
        "tests/fixtures/oracles/core/core-ring-serial-next.txt",
        DIGEST_CORE_RING_SERIAL_NEXT,
        Frontier::KeyRingState,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            outcome(
                msgriver_core::ring::serial_next(o.u64("high_water")?),
                o,
                |v| *v == o.u64("expect_value").unwrap_or(0),
            )
        },
    )
}

#[test]
fn core_ready_both_exhausted() -> Result<(), TestCaseError> {
    case(
        "CORE-READY-BOTH-EXHAUSTED",
        "tests/fixtures/oracles/core/core-ready-both-exhausted.txt",
        DIGEST_CORE_READY_BOTH_EXHAUSTED,
        Frontier::ReadinessReason,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            let guarded = o.u64("guarded")?;
            outcome(
                msgriver_core::incarnation::readiness_exhaustion_both(
                    o.u64("high_water")?,
                    &[guarded],
                ),
                o,
                |(first, second)| {
                    readiness_label(*first) == o.req("expect_first").unwrap_or("")
                        && readiness_label(*second) == o.req("expect_second").unwrap_or("")
                },
            )
        },
    )
}

#[test]
fn core_ring_serial_exhausted() -> Result<(), TestCaseError> {
    case(
        "CORE-RING-SERIAL-EXHAUSTED",
        "tests/fixtures/oracles/core/core-ring-serial-exhausted.txt",
        DIGEST_CORE_RING_SERIAL_EXHAUSTED,
        Frontier::KeyRingState,
        |o: &Oracle| -> Result<CompareResult, TestCaseError> {
            outcome(
                msgriver_core::ring::serial_next(o.u64("high_water")?),
                o,
                |v| *v == o.u64("expect_value").unwrap_or(0),
            )
        },
    )
}
